// src/utils/icons.jsx
// Ilova bo'ylab ishlatiladigan barcha ikonkalar shu yerda react-icons orqali
// markazlashtirilgan — emoji o'rniga.
import {
  FaUtensils,
  FaHeart,
  FaRegHeart,
  FaArrowRight,
  FaArrowLeft,
  FaGlobeAmericas,
  FaStar,
  FaRegStar,
  FaUser,
  FaUsers,
  FaVideo,
  FaCommentDots,
  FaChartLine,
  FaChartBar,
  FaTools,
  FaEdit,
  FaCheck,
  FaTimes,
  FaSearch,
  FaMoon,
  FaSun,
  FaClock,
  FaHourglassHalf,
  FaBell,
  FaInfoCircle,
  FaBook,
  FaCarrot,
} from "react-icons/fa";
import { GiSaltShaker, GiChefToque, GiFriedEggs, GiCompass } from "react-icons/gi";
import { HiOutlineX } from "react-icons/hi";

export const Icons = {
  utensils: FaUtensils,
  heart: FaHeart,
  heartOutline: FaRegHeart,
  arrowRight: FaArrowRight,
  arrowLeft: FaArrowLeft,
  globe: FaGlobeAmericas,
  star: FaStar,
  starOutline: FaRegStar,
  user: FaUser,
  users: FaUsers,
  video: FaVideo,
  comment: FaCommentDots,
  chartLine: FaChartLine,
  chartBar: FaChartBar,
  tools: FaTools,
  edit: FaEdit,
  check: FaCheck,
  close: FaTimes,
  search: FaSearch,
  moon: FaMoon,
  sun: FaSun,
  clock: FaClock,
  hourglass: FaHourglassHalf,
  bell: FaBell,
  info: FaInfoCircle,
  saltShaker: GiSaltShaker,
  chefHat: GiChefToque,
  friedEgg: GiFriedEggs,
  compass: GiCompass,
  clear: HiOutlineX,
  book: FaBook,
  carrot: FaCarrot,
};

export default Icons;
